"""crear modulo de catas

Revision ID: 03fca06745a9
Revises: 293e7088b9fc
Create Date: 2026-03-17 21:30:34.785928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03fca06745a9'
down_revision = '293e7088b9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesion_cata',
    sa.Column('id_sesion_cata', sa.Integer(), nullable=False),
    sa.Column('id_bache', sa.Integer(), nullable=False),
    sa.Column('codigo_publico', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_por', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_bache'], ['bache.id_bache'], ),
    sa.PrimaryKeyConstraint('id_sesion_cata'),
    sa.UniqueConstraint('codigo_publico')
    )
    op.create_table('respuesta_cata',
    sa.Column('id_respuesta_cata', sa.Integer(), nullable=False),
    sa.Column('id_sesion_cata', sa.Integer(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('rango_edad', sa.String(length=50), nullable=True),
    sa.Column('nacionalidad', sa.String(length=20), nullable=True),
    sa.Column('puntaje_color', sa.SmallInteger(), nullable=False),
    sa.Column('puntaje_carbonatacion_espuma', sa.SmallInteger(), nullable=False),
    sa.Column('puntaje_sabor', sa.SmallInteger(), nullable=False),
    sa.Column('puntaje_aroma', sa.SmallInteger(), nullable=False),
    sa.Column('puntaje_impresion_general', sa.SmallInteger(), nullable=False),
    sa.Column('color_valor', sa.SmallInteger(), nullable=False),
    sa.Column('color_categoria', sa.String(length=20), nullable=True),
    sa.Column('carbonatacion_nivel', sa.String(length=10), nullable=False),
    sa.Column('espuma_nivel', sa.String(length=10), nullable=False),
    sa.Column('cuerpo_nivel', sa.String(length=10), nullable=True),
    sa.Column('impresion_general_texto', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion_cata'], ['sesion_cata.id_sesion_cata'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_respuesta_cata')
    )
    op.create_table('respuesta_cata_aroma',
    sa.Column('id_respuesta_cata_aroma', sa.Integer(), nullable=False),
    sa.Column('id_respuesta_cata', sa.Integer(), nullable=False),
    sa.Column('aroma', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_respuesta_cata'], ['respuesta_cata.id_respuesta_cata'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_respuesta_cata_aroma')
    )
    op.create_table('respuesta_cata_sabor',
    sa.Column('id_respuesta_cata_sabor', sa.Integer(), nullable=False),
    sa.Column('id_respuesta_cata', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_respuesta_cata'], ['respuesta_cata.id_respuesta_cata'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_respuesta_cata_sabor')
    )
    with op.batch_alter_table('barril', schema=None) as batch_op:
        batch_op.alter_column('estado_actual',
               existing_type=postgresql.ENUM('NUEVO', 'VACIO', 'LLENO', 'EN_CLIENTE', 'FUERA_SERVICIO', 'LIMPIO', 'ENTREGADO', 'DEVUELTO', 'SUCIO', 'MANTENIMIENTO', 'BAJA', name='estado_barril'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barril', schema=None) as batch_op:
        batch_op.alter_column('estado_actual',
               existing_type=postgresql.ENUM('NUEVO', 'VACIO', 'LLENO', 'EN_CLIENTE', 'FUERA_SERVICIO', 'LIMPIO', 'ENTREGADO', 'DEVUELTO', 'SUCIO', 'MANTENIMIENTO', 'BAJA', name='estado_barril'),
               nullable=True)

    op.drop_table('respuesta_cata_sabor')
    op.drop_table('respuesta_cata_aroma')
    op.drop_table('respuesta_cata')
    op.drop_table('sesion_cata')
    # ### end Alembic commands ###
