"""Quitar bache_origen de bache_levadura_uso

Revision ID: 08374152063a
Revises: 5673c1b381f6
Create Date: 2026-03-02 22:30:11.219330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08374152063a'
down_revision = '5673c1b381f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bache_levadura_uso', schema=None) as batch_op:
        batch_op.alter_column('fecha_inoculacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_bache_levadura_uso_id_bache'), ['id_bache'], unique=False)
        batch_op.create_index(batch_op.f('ix_bache_levadura_uso_id_lote'), ['id_lote'], unique=False)
        batch_op.create_unique_constraint('uq_bache_lote_levadura', ['id_bache', 'id_lote'])
        batch_op.drop_constraint(batch_op.f('bache_levadura_uso_id_bache_origen_fkey'), type_='foreignkey')
        batch_op.drop_column('id_bache_origen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bache_levadura_uso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_bache_origen', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('bache_levadura_uso_id_bache_origen_fkey'), 'bache', ['id_bache_origen'], ['id_bache'], ondelete='SET NULL')
        batch_op.drop_constraint('uq_bache_lote_levadura', type_='unique')
        batch_op.drop_index(batch_op.f('ix_bache_levadura_uso_id_lote'))
        batch_op.drop_index(batch_op.f('ix_bache_levadura_uso_id_bache'))
        batch_op.alter_column('fecha_inoculacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
