"""Agregar ph_macerado y ph_fin_hervido a bache

Revision ID: 0af503ba8d82
Revises: de9ea4d9d472
Create Date: 2026-02-23 20:28:56.305328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af503ba8d82'
down_revision = 'de9ea4d9d472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph_macerado', sa.Numeric(precision=4, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ph_fin_hervido', sa.Numeric(precision=4, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bache', schema=None) as batch_op:
        batch_op.drop_column('ph_fin_hervido')
        batch_op.drop_column('ph_macerado')

    # ### end Alembic commands ###
