"""Simplificar medicion_bache: fecha, sin dia ni unidad

Revision ID: 75918deef0ae
Revises: 0af503ba8d82
Create Date: 2026-02-23 21:54:56.484813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75918deef0ae'
down_revision = '0af503ba8d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicion_bache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=False))
        batch_op.drop_column('unidad')
        batch_op.drop_column('fecha_hora')
        batch_op.drop_column('dia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicion_bache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_hora', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('unidad', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
