"""Modelos de baches y barriles

Revision ID: 90753573d265
Revises: 9efb97ebfb42
Create Date: 2025-12-02 18:59:59.744121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90753573d265'
down_revision = '9efb97ebfb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('BAR', 'RESTAURANTE', 'EVENTO', 'TAPROOM_INTERNO', 'OTRO', name='tipo_cliente'), nullable=True),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('receta',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('estilo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('volumen_estandar_litros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_table('tipo_barril',
    sa.Column('id_tipo_barril', sa.Integer(), nullable=False),
    sa.Column('capacidad_litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_barril')
    )
    op.create_table('bache',
    sa.Column('id_bache', sa.Integer(), nullable=False),
    sa.Column('codigo_bache', sa.String(length=100), nullable=False),
    sa.Column('nombre_cerveza', sa.String(length=100), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=True),
    sa.Column('fecha_coccion', sa.Date(), nullable=False),
    sa.Column('volumen_objetivo_litros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volumen_final_litros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('densidad_inicial', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('densidad_final', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('estado', sa.Enum('PLANIFICADO', 'EN_CURSO', 'FERMENTANDO', 'MADURANDO', 'LISTO', 'COMPLETADO', 'DESCARTADO', name='estado_bache'), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id_receta'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_bache'),
    sa.UniqueConstraint('codigo_bache')
    )
    op.create_table('barril',
    sa.Column('id_barril', sa.Integer(), nullable=False),
    sa.Column('codigo_barril', sa.String(length=100), nullable=False),
    sa.Column('id_tipo_barril', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('estado_actual', sa.Enum('NUEVO', 'VACIO', 'LLENO', 'EN_CLIENTE', 'FUERA_SERVICIO', name='estado_barril'), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_barril'], ['tipo_barril.id_tipo_barril'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_barril'),
    sa.UniqueConstraint('codigo_barril')
    )
    op.create_table('bache_levadura_uso',
    sa.Column('id_bache_levadura', sa.Integer(), nullable=False),
    sa.Column('id_bache', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('tipo_uso', sa.Enum('NUEVA', 'REUTILIZADA', name='tipo_uso_levadura'), nullable=False),
    sa.Column('generacion', sa.SmallInteger(), nullable=False),
    sa.Column('id_bache_origen', sa.Integer(), nullable=True),
    sa.Column('fecha_inoculacion', sa.DateTime(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_bache'], ['bache.id_bache'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_bache_origen'], ['bache.id_bache'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_lote'], ['lote_materia_prima.id_lote'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_bache_levadura')
    )
    op.create_table('bache_materia_prima',
    sa.Column('id_bache_materia', sa.Integer(), nullable=False),
    sa.Column('id_bache', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('cantidad_usada', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad', sa.Enum('KG', 'G', 'L', 'ML', 'UNIDAD', name='unidad_bmp'), nullable=False),
    sa.Column('etapa_proceso', sa.Enum('MACERACION', 'HERVOR', 'WHIRLPOOL', 'FERMENTACION', 'MADURACION', 'OTRA', name='etapa_proceso_bmp'), nullable=False),
    sa.Column('tipo_aplicacion', sa.Enum('GENERAL', 'AMARGOR', 'SABOR', 'AROMA', 'DRY_HOP', 'NUTRIENTE', 'OTRA', name='tipo_aplicacion_bmp'), nullable=False),
    sa.Column('tiempo_minutos_desde_inicio_hervor', sa.Integer(), nullable=True),
    sa.Column('dias_desde_inicio_fermentacion', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_bache'], ['bache.id_bache'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_lote'], ['lote_materia_prima.id_lote'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_bache_materia')
    )
    op.create_table('medicion_bache',
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.Column('id_bache', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PH', 'TEMPERATURA', 'DENSIDAD', 'OTRO', name='tipo_medicion_bache'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_bache'], ['bache.id_bache'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_medicion')
    )
    op.create_table('movimiento_barril',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_barril', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('INGRESO', 'LLENADO', 'SALIDA_CLIENTE', 'RETORNO_VACIO', 'BAJA', 'MANTENIMIENTO', name='tipo_movimiento_barril'), nullable=False),
    sa.Column('id_bache', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('volumen_litros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_bache'], ['bache.id_bache'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_barril'], ['barril.id_barril'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento_barril')
    op.drop_table('medicion_bache')
    op.drop_table('bache_materia_prima')
    op.drop_table('bache_levadura_uso')
    op.drop_table('barril')
    op.drop_table('bache')
    op.drop_table('tipo_barril')
    op.drop_table('receta')
    op.drop_table('cliente')
    # ### end Alembic commands ###
