"""Tablas materias primas

Revision ID: 9efb97ebfb42
Revises: 
Create Date: 2025-12-02 18:36:55.417271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efb97ebfb42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia_prima',
    sa.Column('id_materia_prima', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('MALTA', 'LUPULO', 'LEVADURA', 'OTRO', name='tipo_materia_prima'), nullable=False),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('origen', sa.String(length=100), nullable=True),
    sa.Column('unidad_base', sa.Enum('KG', 'G', 'L', 'ML', 'UNIDAD', name='unidad_base_materia'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_materia_prima')
    )
    op.create_table('levadura_detalle',
    sa.Column('id_materia_prima', sa.Integer(), nullable=False),
    sa.Column('tipo_levadura', sa.Enum('ALE', 'LAGER', 'KVEIK', 'HIBRIDA', 'OTRA', name='tipo_levadura'), nullable=True),
    sa.Column('forma', sa.Enum('SECA', 'LIQUIDA', name='forma_levadura'), nullable=True),
    sa.Column('floculacion', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='floculacion_levadura'), nullable=False),
    sa.Column('atenuacion_min', sa.SmallInteger(), nullable=True),
    sa.Column('atenuacion_max', sa.SmallInteger(), nullable=True),
    sa.Column('pitch_rate_mill_cel_ml_plato', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperatura_min_c', sa.SmallInteger(), nullable=True),
    sa.Column('temperatura_max_c', sa.SmallInteger(), nullable=True),
    sa.Column('notas_estilo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia_prima'], ['materia_prima.id_materia_prima'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_materia_prima')
    )
    op.create_table('lote_materia_prima',
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id_materia_prima', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=100), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('cantidad_inicial', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('generacion_actual', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia_prima'], ['materia_prima.id_materia_prima'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_lote')
    )
    op.create_table('lupulo_detalle',
    sa.Column('id_materia_prima', sa.Integer(), nullable=False),
    sa.Column('uso', sa.Enum('AMARGOR', 'AROMA', 'DUAL', name='uso_lupulo'), nullable=True),
    sa.Column('forma', sa.Enum('PELLET', 'FLOR', 'EXTRACTO', name='forma_lupulo'), nullable=True),
    sa.Column('alfa_acidos_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('beta_acidos_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cohumulona_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aceites_totales_ml_100g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('perfil_aroma', sa.String(length=200), nullable=True),
    sa.Column('año_cosecha', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia_prima'], ['materia_prima.id_materia_prima'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_materia_prima')
    )
    op.create_table('malta_detalle',
    sa.Column('id_materia_prima', sa.Integer(), nullable=False),
    sa.Column('tipo_malta', sa.Enum('BASE', 'CARAMELO', 'TOSTADA', 'ESPECIAL', 'OTRA', name='tipo_malta'), nullable=True),
    sa.Column('color_ebc', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('color_lovibond', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('potencial_gravedad', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('proteinas_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ph_mosto_color', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('uso_max_pct_molienda', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_materia_prima'], ['materia_prima.id_materia_prima'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_materia_prima')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('malta_detalle')
    op.drop_table('lupulo_detalle')
    op.drop_table('lote_materia_prima')
    op.drop_table('levadura_detalle')
    op.drop_table('materia_prima')
    # ### end Alembic commands ###
