"""Eliminar densidad_final y agregar temperaturas de maceracion

Revision ID: d64aa80c5520
Revises: 75918deef0ae
Create Date: 2026-02-24 11:25:58.260676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd64aa80c5520'
down_revision = '75918deef0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_maceracion', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('temp_mashoff', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.drop_column('densidad_final')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('densidad_final', mysql.DECIMAL(precision=6, scale=3), nullable=True))
        batch_op.drop_column('temp_mashoff')
        batch_op.drop_column('temp_maceracion')

    # ### end Alembic commands ###
