"""Agregar tabla otros_mtp_detalle

Revision ID: de9ea4d9d472
Revises: 90753573d265
Create Date: 2025-12-03 11:01:07.494004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9ea4d9d472'
down_revision = '90753573d265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otros_mtp_detalle',
    sa.Column('id_materia_prima', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('SALES', 'ADJUNTOS', 'EXTRACTOS', 'FRUTAS', name='tipo_otro_mtp'), nullable=False),
    sa.ForeignKeyConstraint(['id_materia_prima'], ['materia_prima.id_materia_prima'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_materia_prima')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otros_mtp_detalle')
    # ### end Alembic commands ###
