"""ajustes modulo de catas

Revision ID: e08df6768747
Revises: 03fca06745a9
Create Date: 2026-03-17 22:16:34.278397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08df6768747'
down_revision = '03fca06745a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta_cata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amargor_nivel', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta_cata', schema=None) as batch_op:
        batch_op.drop_column('amargor_nivel')

    # ### end Alembic commands ###
